# Generated by Django 6.1.1 on 2026-09-30 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competences', '0001_initial'),
        ('medias', '0001_initial'),
        ('utilisateurs', '0002_profil_cv_profil_photo_profil_seo_image_defaut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('organisme', models.CharField(blank=True, max_length=200, verbose_name='Organisme')),
                ('date_obtention', models.DateField(verbose_name="Date d'obtention")),
                ('date_expiration', models.DateField(blank=True, help_text="Laisser vide si la certification n'expire pas.", null=True, verbose_name="Date d'expiration")),
                ('identifiant', models.CharField(blank=True, help_text='Numéro ou identifiant de la certification.', max_length=100, verbose_name='Identifiant')),
                ('url_verification', models.URLField(blank=True, max_length=500, verbose_name='URL de vérification')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='medias.media', verbose_name='Badge')),
                ('competences', models.ManyToManyField(blank=True, related_name='certifications', to='competences.competence', verbose_name='Compétences')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='utilisateurs.profil', verbose_name='Profil')),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['-date_obtention', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Parcours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('type', models.CharField(choices=[('experience', 'Expérience professionnelle'), ('formation', 'Formation')], max_length=20, verbose_name='Type')),
                ('organisation', models.CharField(blank=True, max_length=200, verbose_name='Organisation')),
                ('lieu', models.CharField(blank=True, max_length=150, verbose_name='Lieu')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, help_text='Laisser vide si en cours.', null=True, verbose_name='Date de fin')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('competences', models.ManyToManyField(blank=True, related_name='parcours', to='competences.competence', verbose_name='Compétences')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcours', to='utilisateurs.profil', verbose_name='Profil')),
            ],
            options={
                'verbose_name': 'Parcours',
                'verbose_name_plural': 'Parcours',
                'ordering': ['-date_debut', 'ordre'],
            },
        ),
    ]
