# Generated by Django 6.1.1 on 2026-09-28 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0001_initial'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='cv',
            field=models.ForeignKey(blank=True, help_text='Fichier PDF téléchargeable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='medias.media', verbose_name='CV (PDF)'),
        ),
        migrations.AddField(
            model_name='profil',
            name='photo',
            field=models.ForeignKey(blank=True, help_text="Image affichée sur la page d'accueil.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='medias.media', verbose_name='Photo de profil'),
        ),
        migrations.AddField(
            model_name='profil',
            name='seo_image_defaut',
            field=models.ForeignKey(blank=True, help_text="Image Open Graph utilisée si un contenu n'a pas la sienne.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='medias.media', verbose_name='Image SEO par défaut'),
        ),
    ]
