# Generated by Django 6.1.1 on 2026-09-28 12:07

import django.db.models.deletion
import medias.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to=medias.models.media_upload_path, verbose_name='Fichier')),
                ('nom_original', models.CharField(blank=True, max_length=255, verbose_name="Nom d'origine")),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='Type MIME')),
                ('taille', models.PositiveBigIntegerField(default=0, verbose_name='Taille (octets)')),
                ('hash_sha256', models.CharField(blank=True, help_text='Sert à détecter les doublons.', max_length=64, null=True, unique=True, verbose_name='Empreinte SHA-256')),
                ('type', models.CharField(choices=[('image', 'Image'), ('schema', 'Schéma'), ('pdf', 'PDF'), ('video', 'Vidéo'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name='Type')),
                ('alt_text', models.CharField(blank=True, help_text="Pour l'accessibilité (lecteurs d'écran, SEO).", max_length=255, verbose_name='Texte alternatif')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploadé le')),
                ('est_orphelin', models.BooleanField(default=False, help_text='Aucun contenu ne référence ce média (mis à jour par une commande).', verbose_name='Orphelin')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medias_uploades', to=settings.AUTH_USER_MODEL, verbose_name='Uploadé par')),
            ],
            options={
                'verbose_name': 'Média',
                'verbose_name_plural': 'Médias',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='LienExterne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField(verbose_name="ID de l'objet")),
                ('type', models.CharField(choices=[('github', 'GitHub'), ('demo', 'Démonstration'), ('documentation', 'Documentation'), ('video', 'Vidéo'), ('article', 'Article externe'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name='Type')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='Libellé')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Type de contenu')),
            ],
            options={
                'verbose_name': 'Lien externe',
                'verbose_name_plural': 'Liens externes',
                'ordering': ['ordre', 'id'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='medias_lien_content_561e04_idx')],
            },
        ),
        migrations.CreateModel(
            name='MediaLien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField(verbose_name="ID de l'objet")),
                ('role', models.CharField(choices=[('couverture', 'Couverture'), ('illustration', 'Illustration'), ('schema', 'Schéma'), ('capture', "Capture d'écran"), ('autre', 'Autre')], default='illustration', max_length=20, verbose_name='Rôle')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('légende', models.CharField(blank=True, max_length=255, verbose_name='Légende')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Type de contenu')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens', to='medias.media', verbose_name='Média')),
            ],
            options={
                'verbose_name': 'Lien média',
                'verbose_name_plural': 'Liens médias',
                'ordering': ['ordre', 'id'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='medias_medi_content_e15eaa_idx')],
            },
        ),
    ]
