# Generated by Django 6.1.1 on 2026-09-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('sujet', models.CharField(max_length=200, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('ip_hash', models.CharField(blank=True, help_text="Jamais l'IP en clair (RGPD).", max_length=64, verbose_name='Empreinte IP (SHA-256)')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='User-Agent')),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('lu', 'Lu'), ('traite', 'Traité'), ('spam', 'Spam')], default='nouveau', max_length=20, verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-date_envoi'],
            },
        ),
    ]
