# Generated by Django 6.1.1 on 2026-09-30 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login_success', 'Connexion réussie'), ('login_failed', 'Connexion échouée'), ('logout', 'Déconnexion'), ('permission_denied', 'Permission refusée'), ('content_created', 'Contenu créé'), ('content_updated', 'Contenu modifié'), ('content_published', 'Contenu publié'), ('content_unpublished', 'Contenu dépublié'), ('content_archived', 'Contenu archivé'), ('content_deleted', 'Contenu supprimé'), ('media_uploaded', 'Média uploadé'), ('media_deleted', 'Média supprimé'), ('user_created', 'Utilisateur créé'), ('user_updated', 'Utilisateur modifié'), ('user_deleted', 'Utilisateur supprimé'), ('other', 'Autre')], max_length=30, verbose_name='Action')),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ID de la ressource')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('ip_hash', models.CharField(blank=True, max_length=64, verbose_name='Empreinte IP (SHA-256)')),
                ('resultat', models.CharField(choices=[('succes', 'Succès'), ('echec', 'Échec')], default='succes', max_length=10, verbose_name='Résultat')),
                ('metadonnees', models.JSONField(blank=True, default=dict, help_text='Données contextuelles. NE JAMAIS y mettre de secret.', verbose_name='Métadonnées')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Type de ressource')),
                ('utilisateur', models.ForeignKey(blank=True, help_text='Null pour les actions système ou anonymes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Entrée d'audit",
                'verbose_name_plural': "Journal d'audit",
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date'], name='audits_audi_date_5d4688_idx'), models.Index(fields=['action'], name='audits_audi_action_a590ed_idx'), models.Index(fields=['utilisateur', '-date'], name='audits_audi_utilisa_89e318_idx'), models.Index(fields=['content_type', 'object_id'], name='audits_audi_content_a44dbe_idx')],
            },
        ),
    ]
