# Generated by Django 6.1.1 on 2026-09-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, help_text='Laisser vide pour génération automatique depuis le nom.', max_length=200, verbose_name='Slug')),
                ('type', models.CharField(choices=[('projet', 'Projet'), ('laboratoire', 'Laboratoire'), ('article', 'Article'), ('etude_de_cas', 'Étude de cas')], help_text='Domaine fonctionnel de cette catégorie.', max_length=20, verbose_name='Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['type', 'ordre', 'nom'],
                'constraints': [models.UniqueConstraint(fields=('type', 'slug'), name='unique_slug_par_type_categorie')],
            },
        ),
    ]
