# Generated by Django 6.1.1 on 2026-09-30 08:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competences', '0001_initial'),
        ('etudes_de_cas', '0001_initial'),
        ('medias', '0001_initial'),
        ('technologies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etudedecas',
            options={'ordering': ['ordre', '-date_creation'], 'verbose_name': 'Étude de cas', 'verbose_name_plural': 'Études de cas'},
        ),
        migrations.AddField(
            model_name='etudedecas',
            name='analyse',
            field=models.TextField(blank=True, verbose_name='Analyse'),
        ),
        migrations.AddField(
            model_name='etudedecas',
            name='architecture_texte',
            field=models.TextField(blank=True, verbose_name='Architecture (texte)'),
        ),
        migrations.AddField(
            model_name='etudedecas',
            name='auteur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='etudes_de_cas', to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etudedecas',
            name='choix_techniques',
            field=models.TextField(blank=True, verbose_name='Choix techniques'),
        ),
        migrations.AddField(
            model_name='etudedecas',
            name='competences',
            field=models.ManyToManyField(blank=True, related_name='etudes_de_cas', to='competences.competence', verbose_name='Compétences'),
        ),
        migrations.AddField(
            model_name='etudedecas',
            name='contexte',
            field=models.TextField(blank=True, verbose_name='Contexte'),
        ),
        migrations.AddField(
            model_name='etudedecas',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etudedecas',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AddField(
            model_name='etudedecas',
            name='exigences',
            field=models.TextField(blank=True, verbose_name='Exigences'),
        ),
        migrations.AddField(
            model_name='etudedecas',
            name='implementation',
            field=models.TextField(blank=True, verbose_name='Implémentation'),
        ),
        migrations.AddField(
            model_name='etudedecas',
            name='limites',
            field=models.TextField(blank=True, verbose_name='Limites'),
        ),
        migrations.AddField(
            model_name='etudedecas',
            name='menaces',
            field=models.TextField(blank=True, verbose_name='Menaces'),
        ),
        migrations.AddField(
            model_name='etudedecas',
            name='ordre',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AddField(
            model_name='etudedecas',
            name='probleme',
            field=models.TextField(blank=True, verbose_name='Problème'),
        ),
        migrations.AddField(
            model_name='etudedecas',
            name='publish_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Publication programmée'),
        ),
        migrations.AddField(
            model_name='etudedecas',
            name='recommandations',
            field=models.TextField(blank=True, verbose_name='Recommandations'),
        ),
        migrations.AddField(
            model_name='etudedecas',
            name='resultats',
            field=models.TextField(blank=True, verbose_name='Résultats'),
        ),
        migrations.AddField(
            model_name='etudedecas',
            name='securisation',
            field=models.TextField(blank=True, verbose_name='Sécurisation'),
        ),
        migrations.AddField(
            model_name='etudedecas',
            name='seo_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='Description SEO'),
        ),
        migrations.AddField(
            model_name='etudedecas',
            name='seo_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='medias.media', verbose_name='Image SEO'),
        ),
        migrations.AddField(
            model_name='etudedecas',
            name='seo_titre',
            field=models.CharField(blank=True, max_length=70, verbose_name='Titre SEO'),
        ),
        migrations.AddField(
            model_name='etudedecas',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('en_revision', 'En révision'), ('valide', 'Validé'), ('publie', 'Publié'), ('archive', 'Archivé')], default='brouillon', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='etudedecas',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='etudes_de_cas', to='technologies.technologie', verbose_name='Technologies'),
        ),
        migrations.AddField(
            model_name='etudedecas',
            name='tests',
            field=models.TextField(blank=True, verbose_name='Tests'),
        ),
        migrations.AddField(
            model_name='etudedecas',
            name='unpublish_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dépublication programmée'),
        ),
        migrations.AlterField(
            model_name='etudedecas',
            name='slug',
            field=models.SlugField(blank=True, help_text='Laisser vide pour génération automatique depuis le titre.', max_length=200, unique=True, verbose_name='Slug'),
        ),
    ]
