# Generated by Django 6.1.1 on 2026-09-30 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('competences', '0001_initial'),
        ('medias', '0001_initial'),
        ('technologies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, help_text='Laisser vide pour génération automatique depuis le titre.', max_length=200, unique=True, verbose_name='Slug')),
                ('resume', models.CharField(blank=True, max_length=500, verbose_name='Résumé')),
                ('contenu', models.TextField(blank=True, verbose_name='Contenu (markdown)')),
                ('temps_lecture', models.PositiveIntegerField(default=0, help_text='Calculé automatiquement si laissé à 0.', verbose_name='Temps de lecture (minutes)')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_revision', 'En révision'), ('valide', 'Validé'), ('publie', 'Publié'), ('archive', 'Archivé')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('publish_at', models.DateTimeField(blank=True, null=True, verbose_name='Publication programmée')),
                ('unpublish_at', models.DateTimeField(blank=True, null=True, verbose_name='Dépublication programmée')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('seo_titre', models.CharField(blank=True, max_length=70, verbose_name='Titre SEO')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='Description SEO')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='categories.categorie', verbose_name='Catégorie')),
                ('competences', models.ManyToManyField(blank=True, related_name='articles', to='competences.competence', verbose_name='Compétences')),
                ('seo_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='medias.media', verbose_name='Image SEO')),
                ('technologies', models.ManyToManyField(blank=True, related_name='articles', to='technologies.technologie', verbose_name='Technologies')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['ordre', '-date_creation'],
            },
        ),
    ]
