# Generated by Django 6.1.1 on 2026-09-28 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technologie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('categorie_tech', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('database', 'Base de données'), ('reseau', 'Réseau'), ('securite', 'Sécurité'), ('systeme', 'Système'), ('outil', 'Outil'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name='Catégorie technique')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('url_officielle', models.URLField(blank=True, help_text='Lien vers la documentation ou le site officiel.', max_length=500, verbose_name='URL officielle')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technologies_utilisant', to='medias.media', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Technologie',
                'verbose_name_plural': 'Technologies',
                'ordering': ['categorie_tech', 'ordre', 'nom'],
            },
        ),
    ]
