# Generated by Django 6.1.1 on 2026-09-30 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('competences', '0001_initial'),
        ('etudes_de_cas', '0001_initial'),
        ('laboratoires', '0001_initial'),
        ('medias', '0001_initial'),
        ('technologies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, help_text='Laisser vide pour génération automatique depuis le titre.', max_length=200, unique=True, verbose_name='Slug')),
                ('resume', models.CharField(blank=True, max_length=500, verbose_name='Résumé')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('probleme', models.TextField(blank=True, verbose_name='Problème')),
                ('contexte', models.TextField(blank=True, verbose_name='Contexte')),
                ('objectifs', models.TextField(blank=True, verbose_name='Objectifs')),
                ('architecture_texte', models.TextField(blank=True, verbose_name='Architecture (texte)')),
                ('role', models.CharField(blank=True, max_length=200, verbose_name='Rôle')),
                ('difficulte', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé'), ('expert', 'Expert')], default='intermediaire', max_length=20, verbose_name='Difficulté')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_revision', 'En révision'), ('valide', 'Validé'), ('publie', 'Publié'), ('archive', 'Archivé')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('publish_at', models.DateTimeField(blank=True, null=True, verbose_name='Publication programmée')),
                ('unpublish_at', models.DateTimeField(blank=True, null=True, verbose_name='Dépublication programmée')),
                ('date_realisation', models.DateField(blank=True, null=True, verbose_name='Date de réalisation')),
                ('duree', models.CharField(blank=True, max_length=100, verbose_name='Durée')),
                ('resultats', models.TextField(blank=True, verbose_name='Résultats')),
                ('limites', models.TextField(blank=True, verbose_name='Limites')),
                ('ameliorations_futures', models.TextField(blank=True, verbose_name='Améliorations futures')),
                ('mis_en_avant', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('seo_titre', models.CharField(blank=True, max_length=70, verbose_name='Titre SEO')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='Description SEO')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projets', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projets', to='categories.categorie', verbose_name='Catégorie')),
                ('competences', models.ManyToManyField(blank=True, related_name='projets', to='competences.competence', verbose_name='Compétences')),
                ('etude_de_cas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets', to='etudes_de_cas.etudedecas', verbose_name='Étude de cas liée')),
                ('laboratoire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets', to='laboratoires.laboratoire', verbose_name='Laboratoire lié')),
                ('seo_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='medias.media', verbose_name='Image SEO')),
                ('technologies', models.ManyToManyField(blank=True, related_name='projets', to='technologies.technologie', verbose_name='Technologies')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-mis_en_avant', 'ordre', '-date_realisation'],
            },
        ),
    ]
