# Generated by Django 6.1.1 on 2026-09-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True, verbose_name='Nom')),
                ('domaine', models.CharField(choices=[('reseaux', 'Réseaux'), ('cybersecurite', 'Cybersécurité'), ('systemes', 'Systèmes'), ('automatisation', 'Automatisation'), ('developpement', "Développement d'ingénierie")], max_length=30, verbose_name='Domaine')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
                'ordering': ['domaine', 'ordre', 'nom'],
            },
        ),
    ]
