# Generated by Django 6.1.1 on 2026-09-30 08:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competences', '0001_initial'),
        ('laboratoires', '0001_initial'),
        ('medias', '0001_initial'),
        ('technologies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laboratoire',
            options={'ordering': ['ordre', '-date_creation'], 'verbose_name': 'Laboratoire', 'verbose_name_plural': 'Laboratoires'},
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='ameliorations',
            field=models.TextField(blank=True, verbose_name='Améliorations futures'),
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='analyse_securite',
            field=models.TextField(blank=True, verbose_name='Analyse sécurité'),
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='architecture_texte',
            field=models.TextField(blank=True, verbose_name='Architecture (texte)'),
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='auteur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='laboratoires', to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='competences',
            field=models.ManyToManyField(blank=True, related_name='laboratoires', to='competences.competence', verbose_name='Compétences'),
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='configuration',
            field=models.TextField(blank=True, verbose_name='Configuration'),
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='corrections',
            field=models.TextField(blank=True, verbose_name='Corrections apportées'),
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='difficulte',
            field=models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé'), ('expert', 'Expert')], default='intermediaire', max_length=20, verbose_name='Difficulté'),
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='environnement',
            field=models.TextField(blank=True, verbose_name='Environnement'),
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='incidents_rencontres',
            field=models.TextField(blank=True, verbose_name='Incidents rencontrés'),
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='limites',
            field=models.TextField(blank=True, verbose_name='Limites'),
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='materiel_vm',
            field=models.TextField(blank=True, verbose_name='Matériel / VM utilisés'),
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='objectif',
            field=models.TextField(blank=True, verbose_name='Objectif'),
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='ordre',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='prerequis',
            field=models.TextField(blank=True, verbose_name='Pré-requis'),
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='problematique',
            field=models.TextField(blank=True, verbose_name='Problématique'),
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='publish_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Publication programmée'),
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='resultats',
            field=models.TextField(blank=True, verbose_name='Résultats'),
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='seo_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='Description SEO'),
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='seo_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='medias.media', verbose_name='Image SEO'),
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='seo_titre',
            field=models.CharField(blank=True, max_length=70, verbose_name='Titre SEO'),
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('en_revision', 'En révision'), ('valide', 'Validé'), ('publie', 'Publié'), ('archive', 'Archivé')], default='brouillon', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='laboratoires', to='technologies.technologie', verbose_name='Technologies'),
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='tests',
            field=models.TextField(blank=True, verbose_name='Tests réalisés'),
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='unpublish_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dépublication programmée'),
        ),
        migrations.AlterField(
            model_name='laboratoire',
            name='slug',
            field=models.SlugField(blank=True, help_text='Laisser vide pour génération automatique depuis le titre.', max_length=200, unique=True, verbose_name='Slug'),
        ),
    ]
